version: '3'
services:
  go_training_chat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REPOSITORY=github.com/ozaki-physics/go-training-chat
        # パッケージを作成(一意で慣例のリポジトリの書き方)
    image: go1.15:training_chat
    container_name: go_training
    # env_file:
      # .env/path.env
      # go mod を使うために GOPATH を削除するために path を上書き
    tty: true
    volumes:
      - .:/go/src/github.com/ozaki-physics/go-training-chat
      # コンテナ側は相対パス書けない
    ports:
      - "127.0.0.1:8080:8080"
    # working_dir: "/go/src/github.com/ozaki-physics/go-training-chat"
