version: '3'
services:
  go_training_chat:
    image: golang:1.15
    container_name: go_training
    tty: true
    volumes:
      - ./go_mount_package_learning:/go
      # コンテナ側は相対パス書けない
    ports:
      - "127.0.0.1:8080:8080"
